---
- name: Deploy OBM RPM repository (mirror mode)
  copy: >
      src=resources/obm-release-{{ major_version }}-1.noarch.rpm
      dest=/root/obm-release-{{ major_version }}-1.noarch.rpm
  when: mode == "mirror"
  tags: obm-conf

- name: Enable OBM RPM repository (mirror mode)
  yum: name=/root/obm-release-{{ major_version }}-1.noarch.rpm
  when: mode == "mirror"
  tags: obm-conf

- name: Deploy Opush3 RPM repository config file
  copy: >
        src=opush.repo
        dest=/etc/yum.repos.d/opush.repo
  when: major_version | version_compare('3.0', '>=')
  tags: obm-conf

- name: Spoof OBM RPM repository hostname in /etc/hosts (mirror mode)
  lineinfile: >
              dest=/etc/hosts
              regexp='.*packages\.obm\.org$'
              line="{{ packages_mirror_ip }}    packages.obm.org"
  when: mode == "mirror"
  tags: obm-conf

- name: Enable OBM RPM repository (internet mode) [with proxy]
  yum: name=http://rpm.obm.org/release/obm-release-{{ major_version }}-1.noarch.rpm
  environment: proxy_env
  when: mode == "internet" and proxy_host is defined
  tags: obm-conf

- name: Enable OBM RPM repository (internet mode) [without proxy]
  yum: name=http://rpm.obm.org/release/obm-release-{{ major_version }}-1.noarch.rpm
  environment: proxy_env
  when: mode == "internet" and proxy_host is not defined
  tags: obm-conf

- name: Remove any OBM RPM hostname spoofing (internet mode)
  lineinfile: >
              dest=/etc/hosts
              regexp='.*packages\.obm\.org$'
              state=absent
  when: mode == "internet"
  notify:
   - Clean yum repositories
  tags: obm-conf
