---
- name: Create applied updates list if needed
  file: path={{ updatesdir }}/applied_updates.txt  state=touch
  changed_when: False
  delegate_to: "{{ db_master_host }}"
  tags: obm-db

- name: Fetch applied updates list
  fetch: >
   src={{ updatesdir }}/applied_updates.txt
   dest=collected_files
  changed_when: False
  delegate_to: "{{ db_master_host }}"
  tags: obm-db

- name: Read applied updates list
  command: cat {{ updatesdir }}/applied_updates.txt
  changed_when: False
  register: applied_updates
  delegate_to: "{{ db_master_host }}"
  tags: obm-db

- name: List DB update scripts
  command: ls -1 {{ updatesdir }} --hide=*mysql* --hide=*applied*
  changed_when: False
  register: available_updates
  delegate_to: "{{ db_master_host }}"
  tags: obm-db

- name: Apply remaining DB updates
  command: psql -f {{ updatesdir }}/{{ item }}
  environment: "{{ pg_env }}"
  with_items: "{{ available_updates.stdout_lines }}"
  when: "item not in applied_updates.stdout_lines"
  register: command_result
  delegate_to: "{{ db_master_host }}"
  tags: obm-db

- name: Update list of applied updates on remote host
  lineinfile: >
   line={{ item }}
   state=present
   dest={{ updatesdir }}/applied_updates.txt
  with_items: "{{ available_updates.stdout_lines }}"
  when: "item not in applied_updates.stdout_lines"
  delegate_to: "{{ db_master_host }}"
  tags: obm-db
