---
#
# Global configuration file
#

# Don't remove this line
config_version: 0.4

#### Networks definition ####
## Here, you can explicitly declare your lan network IP
## to be sure IP addresses for your services are not taken
## from your management
##
## LAN network : Network used by services
#lan_net: 192.168.122.0
## Admin network : Network used for VM or clusters management
#admin_net: 192.168.100.0

#### SSH Configuration ####
## SSH port needs to be specified if != 22
## because sync module can't read ~/.ssh/config file
## It can be overriden on a per-host basis
## in host_vars/hostname
#obm_ssh_port: 22

#### OBM configuration ####

## OBM version
#obm_version: 3.1.6

## Public URL of the OBM web interface
#obm_external_url: "{{ inventory_hostname }}"

## Database configuration (either PGSQL or MYSQL) (default: PGSQL)
#obm_db_type: PGSQL

## The server hosting the database or the SQL load balancer
#obm_db_host: "{{ groups['dbservers'][0] }}"

## The server hosting the database or the master of replication
#obm_db_master_host: "{{ groups['dbmasters'][0] }}"

## Database configuration
#obm_db_user: obm
#obm_db_pass: obm
#obm_db_name: obm

## Language of the database (fr/en)
#obm_language: fr

#### Cassandra cluster configuration
## Use it only with OBM 3.x
#obm_cassandra_seeds: "{{ hostvars[groups['syncservers'][0]] | get_ip(lan_net) }}"
#obm_cassandra_keyspace: opush
#obm_cassandra_user: opush
#obm_cassandra_password: opush

## The obm-sync host used by obm-ui
#obm_sync_host: "{{ groups['syncservers'][0] }}"

## The opush host used by obm-ui
#obm_opush_host: "{{ groups['opushservers'][0] }}"

## The server hosting the directory or the LDAP load balancer
#obm_ldap_host: "{{ groups['ldapservers'][0] }}"

## The server hosting the directory or the master of replication
#obm_ldap_master_host: "{{ obm_ldap_host }}"

## LDAP directory configuration
#obm_ldap_port: 389
#obm_ldap_ssl: no
#obm_ldap_suffix: "dc=local"

## Customize user in charge of authenticating users
#obm_ldap_bind_dn: "uid=ldapadmin,ou=sysusers,{{ obm_ldap_suffix }}"
#obm_ldap_bind_pw: "mdp3PaAL"

## SASL Backend (allowed values : ldap, pam)
#obm_sasl_backend: "ldap"

## SASL search filter
#obm_sasl_ldap_filter: "(|(&(mailBox=%U@%d)(objectClass=obmUser)(mailAccess=PERMIT))(&(uid=%U)(sn=Cyrus)(objectClass=posixAccount)))"

#### IMAP / SMTP configuration ####
## Globally enable legacy SSL on Messaging services
## by default, only TLS on standard ports will be enable (more secure)
#obm_enable_legacy_ssl: "no"
## Enable POP services (discouraged because it makes backups very difficult)
#obm_enable_pop: "no"

#### IMAP Cluster Configuration ####
## Clustering is automatically enabled if you set a cyrusmupdateserver
## in your inventory.
## You need to set a user for cluster synchronisation. murder will by
## used by default.
## Be carefull : caracters ', " and ; will be automatically removed.
#obm_mupdate_user: murder
#obm_mupdate_pass: murder

#### SSL certificates ####
## If you need a different certificate for an host or a particular
## service, you can override ca_file, cert_file and key_file
## variables in group_vars or host_vars folders.
##
## Default values are specified below
#obm_ca_file:   /var/lib/obm-ca/cacert.pem
#obm_cert_file: /etc/obm/certs/obm_cert.pem
#obm_key_file:  /etc/obm/certs/obm_cert.pem

#### Global NTP server (if needed) ####
## You probably need it if you use mirror mode
#ntp_server: 192.168.122.1

#### Packages mode (default: internet) ####
## Allows you to deploy your architecture without internet access
##
##  internet : get packages from internet repositories (the default)
##  mirror   : add all repositories hostnames in /etc/hosts and make
##             them point to `packages_mirror_ip`.
##  rsync    : rsync resources/rpm-repos directory and install from it [not implemented yet]
##
#packages_mode: internet
#packages_mirror_ip: 192.168.122.1

#### OBM-Autoconf ####
## Allows you to set hostnames published by autoconf
#obm_autoconf_enable: True
#obm_autoconf_smtp_host: "{{ obm_external_url }}"
#obm_autoconf_imap_host: "{{ obm_external_url }}"
#obm_autoconf_ldap_host: "{{ obm_external_url }}""

#### Opush ####
## Authorize synchronization of unknown devices by default
#obm_opush_sync_perms: True

#### Proxy Configuration ####
# Will be deployed on all remote hosts
#proxy_host:
#proxy_port:
#proxy_username:
#proxy_password:

#### Healthcheck Configuration ####
## Healtcheck HTTP Authentication
#healtcheck_login: "admin"
#healtcheck_pass: "linagora"
