---
- name: Init OBM2 Postgres database
  command: psql -f {{ scriptsdir }}/{{item}}
  environment: pg_env
  with_items:
   - setup.sql
   - create_obmdb_{{ major_version }}.pgsql.sql
   - obmdb_default_values_{{ major_version }}.sql
   - murder_user.sql
   - data-{{ language }}/obmdb_ref_{{ major_version }}.sql
   - data-{{ language }}/obmdb_nafcode_{{ major_version }}.sql
   - obmdb_prefs_values_{{ major_version }}.sql
   - lang.sql
  when: major_version | version_compare('3.0', '<')
  delegate_to: "{{ db_master_host }}"
  tags: obm-db-pg

- name: Init OBM3 Postgres database
  command: psql -f {{ scriptsdir }}/{{item}}
  environment: pg_env
  with_items:
   - setup.sql
   - ../creation/create_obmdb.pgsql.sql
   - ../creation/obmdb_default_values.sql
   - murder_user.sql
   - ../creation/data-{{ language }}/obmdb_ref.sql
   - ../creation/data-{{ language }}/obmdb_nafcode.sql
   - ../creation/obmdb_prefs_values.sql
   - lang.sql
   - ../2.5/updates/update-2.5.7~1.pgsql.sql
   - ../2.5/updates/update-2.5.7~2.pgsql.sql
   - ../2.5/updates/update-2.5.8~1.pgsql.sql
   - ../3.0/updates/update-3.0.0~1.pgsql.sql
   - crash_admin.sql
  when: major_version | version_compare('3.0', '>=')
  delegate_to: "{{ db_master_host }}"
  tags: obm-db-pg
