---
- name: Load OS specific vars
  include_vars: "{{ item }}"
  with_first_found:
      - "../vars/{{ ansible_os_family|lower }}.yml"
  ignore_errors: true
  tags:
    - postgres

- name: Load distribution vars
  include_vars: "{{ item }}"
  with_first_found:
      - "../vars/{{ ansible_distribution|lower }}.yml"
  ignore_errors: true
  tags:
    - postgres

- name: Load major version vars
  include_vars: "{{ item }}"
  with_first_found:
      - "../vars/{{ ansible_distribution|lower }}_{{ ansible_distribution_major_version|lower }}.yml"
  ignore_errors: true
  tags:
    - postgres
